### ISSUE TITLE
Call to undefined function trigger_event()

### ISSUE THREAD

**Issue by CodeBrauer** [mistic100/Piwigo-User-Collections#8]
I updated to the newest version of piwigo for PHP7 support, but the plugin causes a fatal error:

```

Fatal error: Uncaught Error: Call to undefined function trigger_event() in /usr/www/users/XXXXXXX/relaunch/plugins/UserCollections/include/events.inc.php:242
Stack trace:
#0 /usr/www/users/XXXXXXX/relaunch/include/functions_plugins.inc.php(279): user_collections_applymenu(Array)
#1 /usr/www/users/XXXXXXX/relaunch/include/block.class.php(194): trigger_notify('blockmanager_ap...', Array)
#2 /usr/www/users/XXXXXXX/relaunch/include/menubar.inc.php(337): BlockManager->apply('MENUBAR', 'menubar.tpl')
#3 /usr/www/users/XXXXXXX/relaunch/include/menubar.inc.php(30): initialize_menu()
#4 /usr/www/users/XXXXXXX/relaunch/index.php(121): include('/usr/www/users/...')
#5 {main} thrown in /usr/www/users/XXXXXXX/relaunch/plugins/UserCollections/include/events.inc.php on line 242
```

**Comment by mistic100** [comment]
It's not related to PHP7 you are using a (very) old version of the plugin. (June 2014 exactly https://github.com/mistic100/Piwigo-User-Collections/commit/fb2b9644a7dc9eb777129bf9255b48910f0dd090)

**Comment by CodeBrauer** [comment]
Oh, somehow I got an old version with the automatic update... redownloaded it manually - fixed. Thanks.
